import { defineSkill } from "@claudecode/skills";

/**
 * GENERATED BY .agents Matrix - DO NOT EDIT MANUALLY
 * Origin: agents_matrix
 */
export default defineSkill({
    id: "agents-start",
    commands: {
        "start": {
            description: "Session-Start Protocol (Keyword: start)",
            handler: async (args, { say }) => {
                await say(`Executing Matrix Workflow: start\nReference: .agents/core/workflows/start_workflow.md`);
                // In a real Claude Code environment, this would trigger the agent to read the file.
                // For now, it acts as an architectural pointer.
            },
        },
    },
});
