import { defineSkill } from "@claudecode/skills";

/**
 * GENERATED BY .agents Matrix - OMNI CONTEXT MINIMIZER
 * Origin: agents_matrix
 */
export default defineSkill({
    id: "agents-skeleton",
    commands: {
        "skeleton": {
            description: "Condenses and extracts the AST skeleton of massive files (>200 lines) saving LLM Context space.",
            handler: async (args, { say }) => {
                await say(`Executing Omni-Context Minimizer via /skeleton.\nReference: .agents/skills/omni-context-minimizer/scripts/omni_minimizer.py`);
                // Engine handles argument parsing natively
            },
        },
    },
});
