import os
import re
from pathlib import Path

# Configuration
WORKFLOW_DIR = Path("core/workflows")
OUTPUT_DIR = Path("skills/commands")
METADATA_REGEX = r"description:\s*\"([^\"]+)\""

def generate_skill_content(cmd_name: str, description: str, workflow_path: str) -> str:
    """Generates the TypeScript content for a Claude Code skill."""
    return f'''import {{ defineSkill }} from "@claudecode/skills";

/**
 * GENERATED BY .agents Matrix - DO NOT EDIT MANUALLY
 * Origin: agents_matrix
 */
export default defineSkill({{
    id: "agents-{cmd_name}",
    commands: {{
        "{cmd_name}": {{
            description: "{description}",
            handler: async (args, {{ say }}) => {{
                await say(`Executing Matrix Workflow: {cmd_name}\\nReference: {workflow_path}`);
                // In a real Claude Code environment, this would trigger the agent to read the file.
                // For now, it acts as an architectural pointer.
            }},
        }},
    }},
}});
'''

def sync():
    """Syncs workflows to slash commands."""
    print("🚀 Initializing Slash Command Synchronization...")
    
    if not WORKFLOW_DIR.exists():
        print(f"❌ Error: Workflow directory {WORKFLOW_DIR} not found.")
        return

    # Check for .claude.code directory
    if not OUTPUT_DIR.parent.exists():
        print(f"⚠️ Warning: {OUTPUT_DIR.parent} not found. Operating in Documentation-Only mode.")
        # We'll create it for local structural verification anyway
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    else:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for workflow_file in WORKFLOW_DIR.glob("*.md"):
        cmd_name = workflow_file.stem
        if cmd_name.startswith("workflow_"):
            cmd_name = cmd_name.replace("workflow_", "")
        
        # Cleanup name (e.g. start_workflow -> start)
        cmd_name = cmd_name.replace("_workflow", "")
        
        content = workflow_file.read_text()
        match = re.search(METADATA_REGEX, content)
        description = match.group(1) if match else f"Triggers the {cmd_name} workflow."

        skill_file = OUTPUT_DIR / f"agents_{cmd_name}.ts"
        skill_content = generate_skill_content(cmd_name, description, f".agents/{workflow_file}")
        
        skill_file.write_text(skill_content)
        print(f"✅ Generated command: /{cmd_name} -> {skill_file.name}")

if __name__ == "__main__":
    sync()
