"""Portable installer for the .agents bridge.

invoked_by: scripts/install.sh, start_workflow.md#bridge_check, hooks/on_init.py.

Cross-platform port of the original bash installer (install.sh is now a
thin wrapper around this). Idempotent: safe to re-run any time.

Usage:
    python3 .agents/scripts/install.py [--profile <name>] [--target claude|cursor|both]

What it does:
  1. Symlinks agents/*.md, commands/*.md and skills/*/ into the host's .claude/
     tree, so Claude Code auto-discovers them (it never reads inside a submodule).
     Falls back to copying when symlinks are unavailable (e.g. Windows without
     Developer Mode) — re-run after submodule updates to refresh copies.
  2. Non-destructively merges claude/settings.hooks.json into the host's
     .claude/settings.json, and claude/mcp.json into the host's .mcp.json.
  3. Appends the constitution import (@.agents/agents.md) to the host CLAUDE.md.
  4. Appends any missing .gitignore entries for the bridge mirror (CLAUDE.md,
     .claude/agents|commands|skills, .claude/settings.local.json) and
     graphify-out/ — everything regenerated locally that must never be
     committed. .claude/settings.json itself is left trackable on purpose:
     it degrades gracefully without the submodule and must survive a fresh
     clone for SessionStart to ever bootstrap the rest.
  5. With --profile: additionally links profiles/<name>/{agents,skills} and
     imports the profile's rules. Profiles are opt-in only.
  6. Marks .agents/.bridge_claude.lock and/or .agents/.bridge_cursor.lock
     (per --target) so hooks/on_init.py and start_workflow bridge_check
     can detect a deliberate submodule update and re-link automatically.
"""
import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
AGENTS_DIR = SCRIPT_DIR.parent
HOST_DIR = AGENTS_DIR.parent

sys.path.insert(0, str(SCRIPT_DIR))
from merge_json import merge  # noqa: E402
import json  # noqa: E402


def link_one(target: str, dest: Path) -> None:
    """Creates dest as a relative symlink to target, never clobbering host content."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.is_symlink():
        try:
            if str(dest.readlink()) == target:
                return  # already correctly linked
        except OSError:
            pass
        print(f"⚠️  Skipping {dest}: exists as a different symlink.")
        return
    if dest.exists():
        print(f"⚠️  Skipping {dest}: already exists and is not our symlink.")
        return
    try:
        dest.symlink_to(target)
        print(f"✅ Linked {dest} -> {target}")
    except OSError:
        # Windows without Developer Mode: degrade to a copy.
        src = (dest.parent / target).resolve()
        if src.is_dir():
            shutil.copytree(src, dest)
        else:
            shutil.copy2(src, dest)
        print(f"✅ Copied (no symlink support) {dest}")


def merge_into(template: Path, dest: Path) -> None:
    template_data = json.loads(template.read_text())
    dest_data = json.loads(dest.read_text()) if dest.exists() else {}
    merged = merge(dest_data, template_data)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(merged, indent=2) + "\n")
    print(f"✅ Merged {template} -> {dest}")


def add_claude_import(import_line: str) -> None:
    claude_md = HOST_DIR / "CLAUDE.md"
    existing = claude_md.read_text() if claude_md.exists() else ""
    if import_line not in existing.splitlines():
        with claude_md.open("a") as f:
            f.write(import_line + "\n")
        print(f"✅ Added import to CLAUDE.md: {import_line}")


# Submodule-dependent bridge mirror (regenerated by this script) and the
# graphify knowledge-graph output (regenerated by its own git hooks on every
# commit/checkout — see skills/graphify/SKILL.md "For git commit hook") must
# never be committed to the host. Found the hard way on a live host: a
# pre-existing broad `settings.json` rule silently swallowed
# .claude/settings.json (which must stay tracked — see below) while leaving
# the actual bridge mirror merely untracked-but-not-ignored, so an accidental
# `git add -A` or a plain `git clean -fd` could commit/wipe it either way;
# separately, graphify-out/ had accumulated 23MB across 20 commits with no
# pruning. `.agents`'s own .gitignore already excludes both for itself
# (nucleus_neutrality doesn't apply here — every host needs this, not just
# the nucleus), so hosts get the same hygiene automatically.
GITIGNORE_ENTRIES = [
    "/CLAUDE.md",
    "/.claude/agents/",
    "/.claude/commands/",
    "/.claude/skills/",
    "/.claude/settings.local.json",
    "/graphify-out/",
]


def ensure_gitignore_entries() -> None:
    """Appends any missing bridge/graphify entries to the host's root
    .gitignore. Idempotent: never touches or reorders existing lines, never
    removes a host's own entries (e.g. if they deliberately track
    graphify-out/ for some reason, re-running this won't fight them — it only
    adds what's absent)."""
    gitignore = HOST_DIR / ".gitignore"
    existing_lines = gitignore.read_text().splitlines() if gitignore.exists() else []
    missing = [e for e in GITIGNORE_ENTRIES if e not in existing_lines]
    if not missing:
        return
    with gitignore.open("a") as f:
        if existing_lines and existing_lines[-1] != "":
            f.write("\n")
        f.write("\n# .agents Claude Code bridge + graphify output (regenerated locally, never commit)\n")
        for entry in missing:
            f.write(entry + "\n")
    print(f"✅ Added {len(missing)} missing .gitignore entr{'y' if len(missing) == 1 else 'ies'} "
          f"for the bridge/graphify output: {', '.join(missing)}")


def scaffold_identity_config() -> None:
    """Copies docs/standards/templates/IDENTITY_TEMPLATE.json to the host root
    as identity.config.json, but only the first time — never touches or merges
    over a host's existing copy (plain existence-guard, same criterion as
    link_one(), not a recursive merge since this is a flat file). Best-effort
    auto-fills repo_slug from `git remote get-url origin`; a missing/foreign
    remote is not a failure, it just leaves repo_slug blank for the human to
    fill in manually. This script never runs render_readme.py itself — that
    stays a deliberate, manual step for the host owner.
    """
    dest = HOST_DIR / "identity.config.json"
    if dest.exists():
        return
    template = AGENTS_DIR / "docs" / "standards" / "templates" / "IDENTITY_TEMPLATE.json"
    data = json.loads(template.read_text())

    try:
        remote_url = subprocess.run(
            ["git", "-C", str(HOST_DIR), "remote", "get-url", "origin"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        match = re.search(r"github\.com[:/](?P<owner>[^/]+)/(?P<repo>.+?)(?:\.git)?/?$", remote_url)
        if match:
            data["repo_slug"] = f"{match.group('owner')}/{match.group('repo')}"
    except (subprocess.CalledProcessError, OSError) as exc:
        print(f"ℹ️  Could not auto-detect repo_slug from 'git remote get-url origin': {exc}")

    dest.write_text(json.dumps(data, indent=2) + "\n")
    print(f"✅ Scaffolded {dest}")
    print("📝 Fill in identity.config.json with your project's details, then run "
          "`.agents/scripts/render_readme.py` manually to generate your README — "
          "the installer never does this automatically.")


BRIDGE_LOCKS_BY_TARGET = {
    "claude": (".bridge_claude.lock",),
    "cursor": (".bridge_cursor.lock",),
    "both": (".bridge_claude.lock", ".bridge_cursor.lock"),
}


def current_submodule_commit() -> str:
    """HEAD of the .agents submodule, or ``unknown`` outside a git context."""
    try:
        return subprocess.run(
            ["git", "-C", str(AGENTS_DIR), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return "unknown"


def write_bridge_locks(target: str) -> None:
    """Record the installed submodule commit in per-target lock files."""
    commit = current_submodule_commit()
    legacy_lock = AGENTS_DIR / ".claude_bridge.lock"
    if legacy_lock.exists():
        legacy_lock.unlink()
    for lock_name in BRIDGE_LOCKS_BY_TARGET[target]:
        lock_path = AGENTS_DIR / lock_name
        lock_path.write_text(commit + "\n")
        print(f"🔒 Bridge installed at commit {commit[:12]}. Marked {lock_path}")


def install_nucleus_bridge() -> int:
    """Minimal self-bridge for the nucleus repo itself: commands + agents +
    constitution import, so `/agents:*` works while developing the framework.
    No hooks (paths are host-relative), no skills links, no MCP, no scaffolding
    — nucleus_neutrality governs structure, not tooling access."""
    print(f"🧬 Nucleus detected — installing minimal self-bridge into {AGENTS_DIR / '.claude'} ...")
    for f in sorted((AGENTS_DIR / "commands").glob("*.md")):
        link_one(f"../../../commands/{f.name}",
                 AGENTS_DIR / ".claude" / "commands" / "agents" / f.name)
    for f in sorted((AGENTS_DIR / "agents").glob("*.md")):
        link_one(f"../../agents/{f.name}", AGENTS_DIR / ".claude" / "agents" / f.name)
    claude_md = AGENTS_DIR / "CLAUDE.md"
    existing = claude_md.read_text() if claude_md.exists() else ""
    if "@agents.md" not in existing.splitlines():
        with claude_md.open("a") as f:
            f.write("@agents.md\n")
        print("✅ Added constitution import to nucleus CLAUDE.md")
    print("🔒 Nucleus self-bridge installed. Restart the Claude Code session to load it.")
    return 0


def install_git_commit_msg() -> None:
    """Install a native commit-msg hook so message gates cover every commit.

    `on_commit.py` runs at pre-commit time, where the message does not yet
    exist — git has not finalised `COMMIT_EDITMSG`, so reading it there would
    test the previous commit's message. The agent path escapes this because its
    Bash command carries `-m`; a terminal or IDE commit had no message gate at
    all. `commit-msg` is the hook that does have it.

    Same ownership rule as the pre-commit installer: an existing hook belongs
    to the project and is never overwritten.
    """
    hooks_dir = HOST_DIR / ".git" / "hooks"
    if not hooks_dir.is_dir():
        return

    hook_path = hooks_dir / "commit-msg"
    body = (
        "#!/usr/bin/env bash\n"
        "# Installed by .agents/scripts/install.py\n"
        "#\n"
        "# Conventional Commit format, regression-test and dependency-\n"
        "# justification gates. pre-commit cannot run these: the message does\n"
        "# not exist yet at that point.\n"
        "set -euo pipefail\n"
        "[ -f .agents/hooks/on_commit_msg.py ] || exit 0\n"
        'exec python3 .agents/hooks/on_commit_msg.py "$1"\n'
    )

    if hook_path.exists():
        current = hook_path.read_text(encoding="utf-8", errors="replace")
        if "on_commit_msg.py" in current:
            return
        print(
            "ℹ️  A commit-msg hook already exists and was left alone. To gate "
            "commit messages too, add:\n"
            '      python3 .agents/hooks/on_commit_msg.py "$1"'
        )
        return

    hook_path.write_text(body, encoding="utf-8")
    hook_path.chmod(0o755)
    print("🪝 Installed .git/hooks/commit-msg (message gates on every commit path)")


def install_git_pre_commit() -> None:
    """Install a native pre-commit hook so a terminal commit is scanned too.

    The secret scanner runs as a Claude Code `PreToolUse` hook, which sees only
    commits the agent makes through its Bash tool. A commit typed in a terminal,
    made from an IDE, or produced by any other tool bypasses it entirely — and
    those are most of the commits in a repository with a human in it.

    Written only when no pre-commit hook exists. An existing one belongs to the
    project and is never overwritten; the path to add is printed instead.
    """
    hooks_dir = HOST_DIR / ".git" / "hooks"
    if not hooks_dir.is_dir():
        return

    hook_path = hooks_dir / "pre-commit"
    body = (
        "#!/usr/bin/env bash\n"
        "# Installed by .agents/scripts/install.py\n"
        "#\n"
        "# The Claude Code PreToolUse hook only sees commits the agent makes.\n"
        "# This covers every other path into the repository.\n"
        "set -euo pipefail\n"
        "[ -f .agents/hooks/on_commit.py ] || exit 0\n"
        "exec python3 .agents/hooks/on_commit.py\n"
    )

    if hook_path.exists():
        current = hook_path.read_text(encoding="utf-8", errors="replace")
        if "on_commit.py" in current:
            return
        print(
            "ℹ️  A pre-commit hook already exists and was left alone. To scan "
            "terminal commits too, add:\n"
            "      python3 .agents/hooks/on_commit.py"
        )
        return

    hook_path.write_text(body, encoding="utf-8")
    hook_path.chmod(0o755)
    print("🪝 Installed .git/hooks/pre-commit (scans terminal commits too)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Install the .agents bridge.")
    parser.add_argument("--profile", help="Optional project profile to install (profiles/<name>)")
    parser.add_argument(
        "--target",
        choices=["claude", "cursor", "both"],
        default="claude",
        help="Installation target: 'claude' (Claude Code, default), 'cursor' (Cursor), or 'both'"
    )
    args = parser.parse_args()

    if args.target != "claude":
        print(
            f"🛑 --target {args.target} is not yet implemented. "
            "The Cursor adapter (scripts/cursor_adapter.py) will wire this in Sprint 026 unit P4.",
            file=sys.stderr
        )
        return 1

    # Nucleus mode (agents.md §5 nucleus_neutrality): the full host bridge is
    # refused, but the minimal self-bridge (commands/agents/constitution) is
    # installed so the framework's own workflows are invocable while developing it.
    if (AGENTS_DIR / ".git").is_dir():
        if args.profile:
            print("🛑 Profiles cannot be installed into the nucleus.", file=sys.stderr)
            return 1
        return install_nucleus_bridge()

    print(f"🌉 Installing Claude Code bridge for .agents into {HOST_DIR} ...")

    for f in sorted((AGENTS_DIR / "agents").glob("*.md")):
        link_one(f"../../.agents/agents/{f.name}", HOST_DIR / ".claude" / "agents" / f.name)

    for f in sorted((AGENTS_DIR / "commands").glob("*.md")):
        link_one(f"../../../.agents/commands/{f.name}",
                 HOST_DIR / ".claude" / "commands" / "agents" / f.name)

    for d in sorted((AGENTS_DIR / "skills").iterdir()):
        if d.is_dir():
            link_one(f"../../.agents/skills/{d.name}", HOST_DIR / ".claude" / "skills" / d.name)

    merge_into(AGENTS_DIR / "claude" / "settings.hooks.json",
               HOST_DIR / ".claude" / "settings.json")
    merge_into(AGENTS_DIR / "claude" / "mcp.json", HOST_DIR / ".mcp.json")

    add_claude_import("@.agents/agents.md")
    ensure_gitignore_entries()
    scaffold_identity_config()
    install_git_pre_commit()
    install_git_commit_msg()

    if args.profile:
        profile_dir = AGENTS_DIR / "profiles" / args.profile
        if not profile_dir.is_dir():
            print(f"🛑 Profile not found: {profile_dir}", file=sys.stderr)
            return 1
        print(f"📦 Installing profile: {args.profile}")
        for f in sorted((profile_dir / "agents").glob("*.md")):
            link_one(f"../../.agents/profiles/{args.profile}/agents/{f.name}",
                     HOST_DIR / ".claude" / "agents" / f.name)
        if (profile_dir / "skills").is_dir():
            for d in sorted((profile_dir / "skills").iterdir()):
                if d.is_dir():
                    link_one(f"../../.agents/profiles/{args.profile}/skills/{d.name}",
                             HOST_DIR / ".claude" / "skills" / d.name)
        for r in sorted((profile_dir / "rules").glob("*.md")):
            add_claude_import(f"@.agents/profiles/{args.profile}/rules/{r.name}")
        if (profile_dir / "mcp" / "registry.json").exists():
            print(f"ℹ️  Profile MCP servers listed in profiles/{args.profile}/mcp/registry.json "
                  "— add the ones you need to .mcp.json manually (they may require API keys).")

    write_bridge_locks(args.target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
