"""Generate the workflow step map and the artifact x workflow matrix.

A hand-maintained map of eleven protocols drifts at the first edit — the exact
failure this phase exists to repair — so it is generated and then verified by
regenerating and comparing (`make verify`). A stale map fails the build instead
of lying quietly.

Three table shapes exist in `workflows/` (`Phase | Step | Action`,
`Phase | Action | Gate`, `Phase | Item | When`), and the ad-hoc extractor used
while planning this phase silently produced nothing for two of them. That is
why the parser is shape-tolerant and why anything it cannot classify is emitted
as `?` rather than guessed: a script that feigns certainty about prose is the
PR #28 defect wearing different clothes.

The matrix columns come from `config/artifact_registry.json` (Sprint 023
`C0.2`). They were a fixed table of six state artifacts and zero documentary
ones, matched against workflow prose by literal filename — so a deliverable a
protocol described in words instead of naming was invisible to this map by
construction, and the producer of `task_scope.md` registered as its consumer.

invoked_by: Makefile `verify` target (regenerate-and-compare).

Usage:
    python3 scripts/map_workflows.py            # write the guide
    python3 scripts/map_workflows.py --check    # fail if the guide is stale

Exit codes:
    0 — guide written, or already current under --check
    1 — under --check, the guide on disk differs from the generated one
"""

import argparse
import json
import re
import sys
from pathlib import Path

WORKFLOWS = Path("workflows")
OUTPUT = Path("docs/guides/WORKFLOWS_STEP_MAP_GUIDE.md")
# Resolved from this file, not from the cwd: the registry is framework data and
# this script is framework-scoped. `C0.3` replaces the expression with a single
# `scripts/_root.py`.
ARTIFACT_REGISTRY = Path(__file__).resolve().parent.parent / "config" / "artifact_registry.json"


def load_artifacts(registry: Path = ARTIFACT_REGISTRY) -> dict[str, str]:
    """Artifact filename -> the phase that produces it, for the matrix columns.

    The columns used to be a fixed table of six state artifacts and zero
    documentary ones, so a protocol's real deliverables — the plan, the sprint
    log, the two assignment records — were invisible to the map by construction.
    They come from `config/artifact_registry.json` now, which is the same list
    the freshness gate and the close gate read.

    Args:
        registry (Path): Path to `config/artifact_registry.json`.

    Returns:
        dict[str, str]: filename -> producing phase, in registry order.

    Raises:
        FileNotFoundError: The registry is absent. Deliberately fatal: a matrix
            silently built with no columns would read as "no workflow touches
            any artifact", which is a false green rather than a missing file.
    """
    data = json.loads(registry.read_text(encoding="utf-8"))
    return {entry["filename"]: entry["phase"] for entry in data["artifacts"]}


ARTIFACTS = load_artifacts()

WRITE_VERBS = ("update", "write", "append", "create", "instantiate", "record",
               "generate", "stamp", "persist", "refresh", "sync", "delete",
               "purge", "rename", "commit", "claim", "release")
READ_VERBS = ("read", "extract", "load", "query", "consult", "parse")
CHECK_VERBS = ("verify", "check", "audit", "validate", "ensure", "confirm",
               "abort", "reject", "scan", "gate")

ROW = re.compile(r"^\|\s*(\*\*)?([^|]+?)(\*\*)?\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$")


def classify(action: str) -> str:
    """read / write / verify, from the action's own verb.

    First match wins by precedence: a step that writes is recorded as a writer
    even when it also reads, because the map exists to expose who writes.
    """
    lowered = action.lower()
    for verbs, label in ((WRITE_VERBS, "write"), (CHECK_VERBS, "verify"), (READ_VERBS, "read")):
        if any(re.search(rf"\b{verb}", lowered) for verb in verbs):
            return label
    return "?"


def parse(path: Path) -> list[tuple[str, str, str]]:
    """(phase, step, action) triples from whichever table shape a workflow uses."""
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ROW.match(line)
        if not match:
            continue
        phase, second, third = match.group(2).strip(), match.group(4).strip(), match.group(5).strip()
        if set(phase) <= set(": -") or phase.lower() == "phase":
            continue  # separator or header
        step = second.strip("`* ")
        rows.append((phase.strip("* "), step, third))
    return rows


def build() -> str:
    lines = [
        "# Workflow Step Map",
        "",
        "> [!IMPORTANT]",
        "> **Generated by `scripts/map_workflows.py`. Do not edit by hand.**",
        "> `make verify` regenerates this file and fails if it differs from the tree.",
        "",
        "Every `/agents:*` protocol, its steps, and what each one does to the shared",
        "artifacts. The `write` column is the diagnostic one: an asymmetry between two",
        "protocols that should mirror each other shows up there first.",
        "",
        "## 1. Artifact x Workflow matrix",
        "",
        "| Workflow | " + " | ".join(ARTIFACTS) + " |",
        "| :--- | " + " | ".join([":---"] * len(ARTIFACTS)) + " |",
    ]

    parsed = {p: parse(p) for p in sorted(WORKFLOWS.glob("*.md"))}

    for path, rows in parsed.items():
        cells = []
        for artifact in ARTIFACTS:
            kinds = {classify(action) for _, _, action in rows if artifact in action}
            cells.append("/".join(sorted(kinds)) if kinds else "—")
        lines.append(f"| `{path.stem}` | " + " | ".join(cells) + " |")

    lines += [
        "",
        "**Columns**, from `config/artifact_registry.json` — the artifact and the phase",
        "that leaves it. A phase is defined by the artifact it leaves, which is what makes",
        "the matrix portable across tools rather than tied to one runner's agent names.",
        "",
    ]
    lines += [f"- `{artifact}` — {phase}" for artifact, phase in ARTIFACTS.items()]

    lines += ["", "## 2. Steps, by protocol", ""]
    for path, rows in parsed.items():
        lines += [f"### `{path.name}`", "", "| Phase | Step | Effect |", "| :--- | :--- | :--- |"]
        for phase, step, action in rows:
            lines.append(f"| {phase} | `{step}` | {classify(action)} |")
        lines.append("")

    lines += [
        "---",
        "*A `?` means the heuristic could not classify that step's verb. It is left",
        "visible rather than guessed — an unclassified step is information, a wrongly",
        "classified one is a lie the next reader inherits.*",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="Fail if the guide is stale.")
    args = parser.parse_args()

    generated = build()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print(f"❌ {OUTPUT} is stale — regenerate with "
                  f"`python3 scripts/map_workflows.py`.", file=sys.stderr)
            return 1
        print(f"✅ {OUTPUT} is current.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"✅ Wrote {OUTPUT}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
