"""Generate the workflow step map and the artifact x workflow matrix.

A hand-maintained map of eleven protocols drifts at the first edit — the exact
failure this phase exists to repair — so it is generated and then verified by
regenerating and comparing (`make verify`). A stale map fails the build instead
of lying quietly.

Three table shapes exist in `workflows/` (`Phase | Step | Action`,
`Phase | Action | Gate`, `Phase | Item | When`), and the ad-hoc extractor used
while planning this phase silently produced nothing for two of them. That is
why the parser is shape-tolerant and why anything it cannot classify is emitted
as `?` rather than guessed: a script that feigns certainty about prose is the
PR #28 defect wearing different clothes.

invoked_by: Makefile `verify` target (regenerate-and-compare).

Usage:
    python3 scripts/map_workflows.py            # write the guide
    python3 scripts/map_workflows.py --check    # fail if the guide is stale

Exit codes:
    0 — guide written, or already current under --check
    1 — under --check, the guide on disk differs from the generated one
"""

import argparse
import re
import sys
from pathlib import Path

WORKFLOWS = Path("workflows")
OUTPUT = Path("docs/guides/WORKFLOWS_STEP_MAP_GUIDE.md")

# Artifacts worth tracking across protocols: the shared state every workflow
# either reads, writes or verifies. Anything not listed is out of scope by
# declaration rather than by oversight.
ARTIFACTS = {
    "active_state.json": "State anchor",
    "task_scope.md": "Subtask ledger",
    "CHANGELOG.md": "Master Ledger",
    "graph.json": "Knowledge graph",
    "memory_index.json": "Distilled knowledge",
    "mirror.json": "State mirror",
}

WRITE_VERBS = ("update", "write", "append", "create", "instantiate", "record",
               "generate", "stamp", "persist", "refresh", "sync", "delete",
               "purge", "rename", "commit", "claim", "release")
READ_VERBS = ("read", "extract", "load", "query", "consult", "parse")
CHECK_VERBS = ("verify", "check", "audit", "validate", "ensure", "confirm",
               "abort", "reject", "scan", "gate")

ROW = re.compile(r"^\|\s*(\*\*)?([^|]+?)(\*\*)?\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$")


def classify(action: str) -> str:
    """read / write / verify, from the action's own verb.

    First match wins by precedence: a step that writes is recorded as a writer
    even when it also reads, because the map exists to expose who writes.
    """
    lowered = action.lower()
    for verbs, label in ((WRITE_VERBS, "write"), (CHECK_VERBS, "verify"), (READ_VERBS, "read")):
        if any(re.search(rf"\b{verb}", lowered) for verb in verbs):
            return label
    return "?"


def parse(path: Path) -> list[tuple[str, str, str]]:
    """(phase, step, action) triples from whichever table shape a workflow uses."""
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ROW.match(line)
        if not match:
            continue
        phase, second, third = match.group(2).strip(), match.group(4).strip(), match.group(5).strip()
        if set(phase) <= set(": -") or phase.lower() == "phase":
            continue  # separator or header
        step = second.strip("`* ")
        rows.append((phase.strip("* "), step, third))
    return rows


def build() -> str:
    lines = [
        "# Workflow Step Map",
        "",
        "> [!IMPORTANT]",
        "> **Generated by `scripts/map_workflows.py`. Do not edit by hand.**",
        "> `make verify` regenerates this file and fails if it differs from the tree.",
        "",
        "Every `/agents:*` protocol, its steps, and what each one does to the shared",
        "artifacts. The `write` column is the diagnostic one: an asymmetry between two",
        "protocols that should mirror each other shows up there first.",
        "",
        "## 1. Artifact x Workflow matrix",
        "",
        "| Workflow | " + " | ".join(ARTIFACTS) + " |",
        "| :--- | " + " | ".join([":---"] * len(ARTIFACTS)) + " |",
    ]

    parsed = {p: parse(p) for p in sorted(WORKFLOWS.glob("*.md"))}

    for path, rows in parsed.items():
        cells = []
        for artifact in ARTIFACTS:
            kinds = {classify(action) for _, _, action in rows if artifact in action}
            cells.append("/".join(sorted(kinds)) if kinds else "—")
        lines.append(f"| `{path.stem}` | " + " | ".join(cells) + " |")

    lines += ["", "## 2. Steps, by protocol", ""]
    for path, rows in parsed.items():
        lines += [f"### `{path.name}`", "", "| Phase | Step | Effect |", "| :--- | :--- | :--- |"]
        for phase, step, action in rows:
            lines.append(f"| {phase} | `{step}` | {classify(action)} |")
        lines.append("")

    lines += [
        "---",
        "*A `?` means the heuristic could not classify that step's verb. It is left",
        "visible rather than guessed — an unclassified step is information, a wrongly",
        "classified one is a lie the next reader inherits.*",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="Fail if the guide is stale.")
    args = parser.parse_args()

    generated = build()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print(f"❌ {OUTPUT} is stale — regenerate with "
                  f"`python3 scripts/map_workflows.py`.", file=sys.stderr)
            return 1
        print(f"✅ {OUTPUT} is current.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"✅ Wrote {OUTPUT}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
